In [1]:
#1
import numpy as np
array=np.arange(50,101)
print("Array of all the even integers from 50 to 100")
print(array)

Array of all the even integers from 50 to 100
[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [2]:
#2
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*6
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


In [41]:
#3
import numpy as np
array=np.arange(20,32)
a = np.reshape(array,(3,4))
print("Array of all the even integers from 20 to 32")
print(a)

Array of all the even integers from 20 to 32
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [38]:
#4
import numpy as np
x = np.diag([1, 1, 1])
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [39]:
#4
import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#5
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [39]:
#6
data1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr1 = np.array(data1)
x = np.sum(arr1)
print(arr1)
print(x)
print(arr1.sum(axis=1))
print(arr1.sum(axis=0))

[[1 2 3 4]
 [5 6 7 8]]
36
[10 26]
[ 6  8 10 12]


In [49]:
#Salaries
KobeBryant_Salary = [27849149,30453805,23500000, 250000000,0,0,0,0,0,0]
JoeJohnson_Salary = [19752645,21466718,23180790, 22309344,11000000,10254904,0,0,0,0]
LeBronJames_Salary = [17545000,19067500,20644400, 22970500,30963450,33285709,35654150,37436858,39219566,0]
CarmeloAnthony_Salary = [19450000,22407474,22458000, 22875000,24559380,26243760,2393887,2159029,2564753,0]
DwightHoward_Salary = [19536360,20513178,21436271,22359364,23180275, 23500000, 24256725, 5443553, 2564753, 2641691]
ChrisBosh_Salary = [17545000,19067500,20644400,22192730, 23741060, 25289390, 26837720, 0,0,0]
ChrisPaul_Salary = [17779458,18668431,20068563,21468695, 22868827,24268959, 35654150, 38506482, 41358814, 30800000]
KevinDurant_Salary = [16669630,17832627,18995624,20158622, 26540100, 25000000, 30000000, 38199000, 38771513, 42018900]
DerrickRose_Salary = [16402500,17632688,18862875, 20093064, 21323252, 2525077, 2393887, 6859756, 7682927, 13445120]
DwayneWade_Salary = [17182000,18673000,15000000, 20000000, 23200000, 17878652, 2393887, 0,0,0]
#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary, CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary, KevinDurant_Salary, DerrickRose_Salary, DwayneWade_Salary])

#Games 
KobeBryant = [78,6,35, 66,0,0,0,0,0,0]
JoeJohnson = [72,79,80, 81,57,24,78,55,0,0]
LeBronJames =[76,77,69, 76,74,82,55,67,45,48]
CarmeloAnthony = [67,77,40, 72,74,78,2,58,3,3]
DwightHoward = [76,71,41, 71,74,81,9,69,69,47]
ChrisBosh = [74,79,44, 53,0,0,0,0,0,0]
ChrisPaul = [70,62,82, 74,61,58,58,70,70,58]
KevinDurant = [81,81,27, 72,62,68,78,0,32,0]
DerrickRose = [0,10,51, 66,64,25,51,50,50,26]
DwayneWade = [69,54,62, 74,60,67,72,0,0,0]
#Matrix
Games = np.array([KobeBryant, JoeJohnson, LeBronJames, CarmeloAnthony, DwightHoward, ChrisBosh, ChrisPaul, KevinDurant, DerrickRose, DwayneWade])
#Field Goals
KobeBryant_FG = [738,31,266, 398, 0,0,0,0]
JoeJohnson_FG = [445,462,446, 377, 273, 146, 0,0]
LeBronJames_FG = [765,767,624, 737, 736, 857, 558, 643 ]
CarmeloAnthony_FG = [669,743,358,567, 602,472, 49, 336 ]
DwightHoward_FG = [470,473,251, 372,388,506,43,202]
ChrisBosh_FG = [485,492,343,358,0,0,0,0]
ChrisPaul_FG = [412,406,568,515, 374, 367, 302, 434]
KevinDurant_FG = [731,849,238,698, 551, 630, 721,0]
DerrickRose_FG = [0,58,338,447, 460, 162, 363, 369]
DwayneWade_FG = [569,415,509, 540, 414, 508, 416,0]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])

In [50]:
print("Total salary of each player:")
print(np.sum(Salary, axis = 0))
print("Total salary of all players :")
print(np.sum(Salary, axis = 1))
print("Total games of each player:")
print(np.sum(Games, axis = 0))
print("Total games of all players:")
print(np.sum(Games, axis = 1))
print("Total field goals of each player:")
print(np.sum(FieldGoals, axis = 0))
print("Total field goals of all players:")
print(np.sum(FieldGoals, axis = 1))

Total salary of each player:
[189711742 205782921 204790923 444427319 207376344 188246451 159584406
 128604678 132162326  88905711]
Total salary of all players :
[331802954 107964401 256787133 145111283 165432170 155317800 271442379
 274186016 127221146 114327539]
Total games of each player:
[663 596 531 705 526 483 403 369 269 182]
Total games of all players:
[185 526 669 474 608 250 663 501 393 458]
Total field goals of each player:
[5284 4696 3941 5009 3798 3648 2452 1984]
Total field goals of all players:
[1433 2149 5687 3796 2705 1678 3378 4418 2197 3371]
